# for when canonical finally handles release upgrade to 22.04
# and podman goes to v4...
# FROM docker.io/library/node:21
# RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
#     --mount=target=/var/cache/apt,type=cache,sharing=locked \
# RUN apt-get update && apt-get install -y graphviz

FROM localhost/node-graphviz:latest

WORKDIR /usr/src/site-builder
COPY package.json package-lock.json .

# hack for buildah 3.x, rquires `buildah -v <hostdir>:/run/node_modules ...`
RUN cp -r /run/node_modules ./node_modules

RUN npm install
# buildah 4.x can use RUN --mount=type=cache,target=/usr/src/site-builder/node_modules/ npm install
COPY builder.ts tsconfig.json .
RUN npx tsc

ENTRYPOINT [ "/usr/local/bin/node", "/usr/src/site-builder/builder.js" ]
